### PR TITLE
[4.0] Permissions as custom element

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue 

### Summary of Changes

move the code to the custom element

### Testing Instructions

Go to Admin Global Configuration and test the permissions

### Expected result
Working as before 

### Actual result
Working as before

### Documentation Changes Required
No

### CODE REVIEW

**Comment by anuragteapot** [comment]
@C-Lodder this also need to be written as ES6 code style ??

**Comment by C-Lodder** [comment]
@dgt41 @dneukirchen Fixed most of the Hound errors, but now getting `Parsing error: Unexpected token sendPermissions`...any idea?

**Comment by anuragteapot** [comment]
@C-Lodder Thanks you save my time :)

**Comment by anuragteapot** [comment]
So, we have to fix all other custom elements in ES6 format.

**Comment by anuragteapot** [comment]
Due to <code>const sendPermissions</code> and <code>const getUrlParam</code>. 

<code>connectedCallback()</code> function should contains both.

**Comment by dneukirchen** [comment]
Is it ok for you when we make the custom-element PRs against main repository? 

I dont want to put too many changes in this repo (it was only created for es6 transformation and we already doing more than planned (inline-scripts)). 

Please close this PR and open it again in main.

**Comment by anuragteapot** [comment]
@dneukirchen Ok

**Comment by dneukirchen** [comment]
thx

**Pull request closed without merging**
