### PR TITLE
Update bootstrap-init.es6.js

### PR DESCRIPTION
**Pull request by C-Lodder**
Redone as the ES6 `for of ` transpiled to something a bit too long.

You'll need to test this though

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Please check the generated transpiled code for ES5. You're adding like 20 lines just to use `for of`.
For me this is a no go

**Comment by C-Lodder** [comment]
@dgt41 - I'm not using `for of`. That's why I closed the other commit and submited this one

**Comment by dneukirchen** [comment]
Please also note that Object.keys requires a polyfill. So if we only keep this file to be bc for 3rd party.... we should probably not use Object.keys, because it will not work when 3dp hasnt polyfilles/shimmed it.

**Comment by C-Lodder** [comment]
@dneukirchen Why does it require a polyfill? It's supported on all browsers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Browser_compatibility

**Comment by dneukirchen** [comment]
@dgt41 this one can be closed as well?

**Comment by dgrammatiko** [comment]
yes, all the files going to legacy should remain ES5.

These files will come with joomla but without any support or guarantee that they will work correctly throughout the lifetime of J4!

**Comment by C-Lodder** [comment]
It's still ES5 (apart from arrow functions), so I can backport this to the original file and properly test at some other time.

**Pull request closed without merging**
