### PR TITLE
Remove inline scripts/components/com content/tmpl/form/edit.php

### PR DESCRIPTION
**Pull request by dneukirchen**
Pull Request for Issue #53

### CODE REVIEW

**Comment by Fedik** [comment]
hm I have suggested a bit another approach in https://github.com/joomla/joomla-cms/pull/19635 (after that patch all JS can be removed here at all):

after that it could be:
```html
<joomla-toolbar-button task="article.save" form="#adminForm" form-validation>
	<button type="button" class="random button class">
		<span class="random icon class" aria-hidden="true"></span> JSAVE
	</button>
</joomla-toolbar-button>

<joomla-toolbar-button task="article.cancel" form="#adminForm">
	<button type="button" class="random button class">
		<span class="random icon class" aria-hidden="true"></span> JCANCEL
	</button>
</joomla-toolbar-button>
```

But it still good as you made :wink:

**Comment by dneukirchen** [comment]
Thx. We definitely need some abstraction for toolbar button listeners. I will checkout the custom element

**Comment by dgrammatiko** [comment]
@dneukirchen try to delete all the inline script without adding anything. Does that work?

**Comment by dneukirchen** [comment]
>  try to delete all the inline script without adding anything. Does that work?

No, that does not work in frontend.

**Review by C-Lodder — APPROVED** [review]

**Comment by dneukirchen** [comment]
im merging this now. We can replace it with the ce, once that is merged (and used in frontend)

**Pull request merged**
